### ISSUE TITLE
dobbiamo implementare e disegnare anche queste pagine?

### ISSUE THREAD

**Issue by capponiFelice92** [capponiFelice92/rubrica-multipag-his#1]
![Interfacce Utente pdf - Personale - Microsoft​ Edge 23_02_2021 18_02_07](https://user-images.githubusercontent.com/78529321/108879387-826a9500-7601-11eb-8194-438f992c6cfd.png)

**Comment by luca-lezzerini** [comment]
No, Login e Errore non sono necessarie

**Comment by capponiFelice92** [comment]
perfetto grazie.
